reject unknown args to powernap
Signed-off-by: Dustin Kirkland <kirkland@canonical.com>

diff --git a/powernap b/powernap
--- a/powernap
+++ b/powernap
@@ -26,6 +26,10 @@ for arg in $@; do
 		-f|--foreground)
 			FOREGROUND=1
 		;;
+		*)
+			echo "Invalid argument"
+			exit 1
+		;;
 	esac
 done
 
